image: julia:1.6-alpine

pages:
  stage: deploy
  script:
  - julia --project docs/make.jl
  artifacts:
    paths:
    - docs/build
  publish: docs/build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH